### ISSUE TITLE
What a surprise, it does not compile

### ISSUE THREAD

**Issue by matipacheco** [Squirrels/c--tic-tac-toe#1]
`c--tic-tac-toe git:(master) g++ main.cpp -o main`
`main.cpp:40:22: error: a space is required between consecutive right angle`
`      brackets (use '> >')`
`    vector<vector<int>> lines{`
`                     ^~`
`                     > >`
`main.cpp:40:30: error: expected ';' at end of declaration`
`    vector<vector<int>> lines{`
`                             ^`
`                             ;`
`2 errors generated.`

**Comment by Squirrels** [comment]
_g++_ assumes **C++03** by default, and the syntax in this code uses **C++11**. 

To compile it without this error, use
`g++ -std=c++11 -o main main.cpp`

Source: [StackOverflow](https://stackoverflow.com/questions/27924050/expected-at-end-of-declaration-vector-c)
